"""
Data models for the API request and response payloads.

The models have been generated from a swagger.json file. Slight modifications have been
made to ensure that the models are compatible with test environment responses.
"""

from pybvvd.api._generated import (
    ApiError,
    AvregistreradOrganisation,
    Avregistreringsorsak,
    Dataproducent,
    DokumentlistaBegaran,
    DokumentlistaSvar,
    DokumentlistaSvarDokumentInner,
    Fel,
    FelTyp,
    Identitetsbeteckning,
    JaNej,
    JuridiskForm,
    KodKlartext,
    Namnskyddslopnummer,
    NaringsgrenOrganisation,
    Organisation,
    OrganisationerBegaran,
    OrganisationerSvar,
    Organisationsdatum,
    Organisationsform,
    Organisationsnamn,
    OrganisationsnamnObjekt,
    Organisationsnamntyp,
    PagaendeAvvecklingsEllerOmstruktureringsforfarande,
    PagaendeAvvecklingsEllerOmstruktureringsforfarandeObjekt,
    Postadress,
    PostadressOrganisation,
    Reklamsparr,
    Sni,
    Verksamhetsbeskrivning,
    VerksamOrganisation,
)

__all__ = (
    "ApiError",
    "AvregistreradOrganisation",
    "Avregistreringsorsak",
    "Dataproducent",
    "DokumentlistaBegaran",
    "DokumentlistaSvar",
    "DokumentlistaSvarDokumentInner",
    "Fel",
    "FelTyp",
    "Identitetsbeteckning",
    "JaNej",
    "JuridiskForm",
    "KodKlartext",
    "Namnskyddslopnummer",
    "NaringsgrenOrganisation",
    "Organisation",
    "OrganisationerBegaran",
    "OrganisationerSvar",
    "Organisationsdatum",
    "Organisationsform",
    "Organisationsnamn",
    "OrganisationsnamnObjekt",
    "Organisationsnamntyp",
    "PagaendeAvvecklingsEllerOmstruktureringsforfarande",
    "PagaendeAvvecklingsEllerOmstruktureringsforfarandeObjekt",
    "Postadress",
    "PostadressOrganisation",
    "Reklamsparr",
    "Sni",
    "VerksamOrganisation",
    "Verksamhetsbeskrivning",
)
