# generated by datamodel-codegen:
#   filename:  patched-swagger.json
#   timestamp: 2026-04-16T08:36:39+00:00

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from datetime import date
from enum import StrEnum


class OrganisationerBegaran(BaseModel):
    """
    An object to specify `identitetsbeteckning` (company registration number).
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    identitetsbeteckning: str


class ApiError(BaseModel):
    """
    Error information. Based on [RFC 7807](https://tools.ietf.org/html/rfc7807).
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    type_: str = Field(..., alias='type', description='One of below:\n* `about:blank`\n* `urn:bolagsverket:error:auth`\n* `urn:bolagsverket:error:network`\n* `urn:bolagsverket:error:validation`\n', examples=['urn:bolagsverket:error:validation'])
    instance: str = Field(..., description='A certain value on `instance` is a unique type of error but also associated with a `type`, that is one value on `instance` shall only occur with a value on `type`.\n\n**General**: `about:blank`\n- `not.found` information not found\n- `server.error` internal server error\n\n**Access control**: `urn:bolagsverket:error:auth`\n- `auth.error` authentication error\n\n**Validation**: `urn:bolagsverket:error:validation`\n- `validation.client` validation error of client request\n\n**Network**: `urn:bolagsverket:error:network`\n- `network.timeout` network timeout\n- `network.error` internal network error\n', examples=['validation.client'])
    status: int = Field(..., description='HTTP status.', examples=[400])
    timestamp: AwareDatetime | None = Field(None, description='Date and time in ISO 8601 format.', examples=['2024-09-18T09:32:24Z'])
    requestId: str | None = Field(None, description='Identity associated with the API call, sent in header X-Request-Id.', examples=['d120654c-0d09-481a-8956-940a76474e6b'])
    title: str = Field(..., description='Short description of the error.', examples=['Bad Request'])
    detail: str | None = Field(None, description='Detailed description of the error.', examples=['JSON parse error'])


class DokumentlistaBegaran(BaseModel):
    """
    An object to specify `identitetsbeteckning` (company registration number) used to retrieve a list of annual reports.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    identitetsbeteckning: str


class Namnskyddslopnummer(RootModel[int]):
    root: int = Field(..., description="'Namnskyddslopnummer' is used to separate companies for organisation types that can have more than one company on the same 'identitetsbeteckning' (company registration number). For example the legal form 'enskild näringsverksamhet' can have more than one company with different names on the same company registration number.", examples=[1], ge=1, le=999, title='Namnskyddslopnummer')


class KodKlartext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: str
    klartext: str


class PagaendeAvvecklingsEllerOmstruktureringsforfarandeObjekt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: str = Field(..., examples=['KK'])
    klartext: str | None = Field(None, examples=['Konkurs'])
    fromDatum: date | None = Field(None, examples=['2024-01-26'])


class Sni(RootModel[KodKlartext]):
    root: KodKlartext


class Postadress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    postnummer: str = Field(..., examples=['12345'])
    utdelningsadress: str | None = Field(None, examples=['Jobbstigen 2'])
    land: str | None = Field(None, examples=['Sverige'])
    coAdress: str | None = Field(None, examples=['C/o Annat företag'])
    postort: str | None = Field(None, examples=['Grönköping'])


class Dataproducent(StrEnum):
    """
    The source of information.
    """
    Bolagsverket = 'Bolagsverket'
    SCB = 'SCB'


class FelTyp(StrEnum):
    """
    A specific error type (`feltyp`) is assigned every error to categorise it.
    """
    ORGANISATION_FINNS_EJ = 'ORGANISATION_FINNS_EJ'
    OGILTIG_BEGARAN = 'OGILTIG_BEGARAN'
    OTILLGANGLIG_UPPGIFTSKALLA = 'OTILLGANGLIG_UPPGIFTSKALLA'
    TIMEOUT = 'TIMEOUT'


class JaNej(StrEnum):
    """
    The parameter can have the value `JA` (yes) or `NEJ` (no).
    """
    JA = 'JA'
    NEJ = 'NEJ'


class DokumentlistaSvarDokumentInner(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dokumentId: str | None = None
    filformat: str | None = None
    rapporteringsperiodTom: date | None = None
    registreringstidpunkt: date | None = None


class DokumentlistaSvar(BaseModel):
    """
    A list of available annual reports.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    dokument: list[DokumentlistaSvarDokumentInner] | None = None


class Identitetsbeteckning(BaseModel):
    """
    Unique identification of an organisation. `Identitetsbeteckning` can be 'organisationsnummer' (company registration number), 'personnummer' (personal identity number), 'samordningsnummer' or 'GD-nummer'. 'Organisationsnummer' is represented by 10 digits, 'personnummer' is represented by 12 digits (YYYYMMDDXXXX), 'samordningsnummer' is represented by 12 digits (YYYYMMDDXXXX, where 'DD' is the persons birthday + 60) and 'GD-nummer' is represented by 10 digits (302XXXXXXX).
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    identitetsbeteckning: str = Field(..., description="A unique set of characters used to identify the registered organisation. In Sweden this is one of 'organisationsnummer', 'personnummer', 'samordningsnummer' or 'gdNummer'.", examples=['5299999994'], pattern='^(19|20)?\\d{2}(0[1-9]|1[0-2])((0|6)[1-9]|(1|2|7|8)[0-9]|(3|9)[0|1])\\d{4}$|^\\d{6}\\d{4}$|^302\\d{8}$')
    typ: KodKlartext


class OrganisationsnamnObjekt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    namn: str | None = Field(None, examples=['Cykelbolaget AB'])
    organisationsnamntyp: KodKlartext | None = None
    registreringsdatum: str | None = Field(None, description='The date the business name was registered.', examples=['2024-03-15'])
    verksamhetsbeskrivningSarskiltForetagsnamn: str | None = Field(None, description='Description of the business activities for the particular business name.', examples=['Att bedriva handel med mopeder.'])


class Organisationsnamntyp(RootModel[KodKlartext]):
    root: KodKlartext


class Fel(BaseModel):
    """
    An error (`fel`) is primarily defined by its type (`feltyp`). To describe the nature of the fault and error, description (`felbeskrivning`) is used.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    typ: FelTyp
    felBeskrivning: str | None = None


class Organisationsnamn(BaseModel):
    """
    The business names associated with the organisation.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    organisationsnamnLista: list[OrganisationsnamnObjekt] | None = None
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Reklamsparr(BaseModel):
    """
    Indicates if the organisation is blocked from receiving advertisement. If the object is null, Bolagsverket have replied with information about postadressOrganisation and no reklamsparr is registered.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: JaNej
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Organisationsform(BaseModel):
    """
    Indicates the administrative form in which an organisation conducts its activities.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: str = Field(..., examples=['AB'], max_length=4, min_length=1)
    klartext: str = Field(..., examples=['Aktiebolag'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class AvregistreradOrganisation(BaseModel):
    """
    The date an organisation was removed from the register.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    avregistreringsdatum: str | None = Field(None, examples=['2023-05-05T00:00:00.000+00:00'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Avregistreringsorsak(BaseModel):
    """
    The reason an organisation was removed from the register.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: str = Field(..., examples=['LIAV'])
    klartext: str = Field(..., examples=['Likvidation'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class PagaendeAvvecklingsEllerOmstruktureringsforfarande(BaseModel):
    """
    Indicates a removal from the register or restructuring procedure that is ongoing or has not been formally finished and that the organisation is in a process of status change.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    pagaendeAvvecklingsEllerOmstruktureringsforfarandeLista: list[PagaendeAvvecklingsEllerOmstruktureringsforfarandeObjekt] | None = None
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class JuridiskForm(BaseModel):
    """
    Legal form registered at the Swedish Tax Agency.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: str | None = Field(None, examples=['49'], max_length=4, min_length=1)
    klartext: str | None = Field(None, examples=['Övriga aktiebolag'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class VerksamOrganisation(BaseModel):
    """
    Indicates if the organisation is active.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    kod: JaNej | None = None
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Organisationsdatum(BaseModel):
    """
    Specifies the date an organisation was registered.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    registreringsdatum: str = Field(..., examples=['2000-01-23'])
    infortHosScb: str | None = Field(None, examples=['2000-02-03'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Verksamhetsbeskrivning(BaseModel):
    """
    Description of the business activities. Can be a lot of text in some cases.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    beskrivning: str = Field(..., examples=['Handel med skor'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class NaringsgrenOrganisation(BaseModel):
    """
    A code that indicates an organisations main business activities.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    sni: list[Sni] = Field(..., examples=['kod = 01120, klartext = Odling av ris'])
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class PostadressOrganisation(BaseModel):
    """
    Registered postal address.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    postadress: Postadress
    dataproducent: Dataproducent | None = None
    fel: Fel | None = None


class Organisation(BaseModel):
    """
    Organisation information including the `identitetsbeteckning` (company registration number) specified in the request, and a series or elements holding the high-value datasets.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    organisationsidentitet: Identitetsbeteckning | None = None
    namnskyddslopnummer: int | None = Field(None, description="'Namnskyddslopnummer' is used to separate companies for organisation types that can have more than one company on the same 'identitetsbeteckning' (company registration number). For example the legal form 'enskild näringsverksamhet' can have more than one company with different names on the same company registration number.", examples=[1], ge=1, le=999, title='Namnskyddslopnummer')
    organisationsnamn: Organisationsnamn | None = None
    registreringsland: KodKlartext | None = None
    reklamsparr: Reklamsparr | None = None
    organisationsform: Organisationsform | None = None
    avregistreradOrganisation: AvregistreradOrganisation | None = None
    avregistreringsorsak: Avregistreringsorsak | None = None
    pagaendeAvvecklingsEllerOmstruktureringsforfarande: PagaendeAvvecklingsEllerOmstruktureringsforfarande | None = None
    juridiskForm: JuridiskForm | None = None
    verksamOrganisation: VerksamOrganisation | None = None
    organisationsdatum: Organisationsdatum | None = None
    verksamhetsbeskrivning: Verksamhetsbeskrivning | None = None
    naringsgrenOrganisation: NaringsgrenOrganisation | None = None
    postadressOrganisation: PostadressOrganisation | None = None


class OrganisationerSvar(BaseModel):
    """
    The response with requested organisation data as a list.
    """
    model_config = ConfigDict(
        extra='forbid',
    )
    organisationer: list[Organisation] | None = None
