name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
      - "README.md"
      - "pybvvd/**"
      - "docs/**"
      - "mkdocs.yml"
      - "readthedocs.yaml"
      - "requirements/docs.txt"
      - ".github/workflows/docs.yml"
      - ".github/actions/set-up-python-env/action.yml"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/set-up-python-env
        with:
          cache-dependency-path: |
            pyproject.toml
            requirements/docs.txt

      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -r requirements/docs.txt

      - name: Build docs
        run: python -m mkdocs build --strict
